package com.flyme2mars.hop.ui.theme

import androidx.compose.ui.graphics.Color

/** True blackout. Cut mode only — not an everyday surface. */
val CutBlack = Color(0xFF000000)

/** Candle accent. Clock and the primary Cut CTA only. */
val CutFlame = Color(0xFFE8B86D)

val CutOnFlame = Color(0xFF1A1206)
val CutOnBlack = Color(0xFFEDE6D6)
val CutOnBlackMuted = Color(0xFFB9B2A4)
val CutOkContainer = Color(0xFF1A1A1A)
val CutOkOnContainer = Color(0xFFE8E8E8)

// Mono fallback when dynamic color is unavailable (pre-Android 12).
// Graphite only — HopGreen / HopSand are retired from product UI.

val MonoLightPrimary = Color(0xFF2C2C2C)
val MonoLightOnPrimary = Color(0xFFFFFFFF)
val MonoLightPrimaryContainer = Color(0xFF3F3F3F)
val MonoLightOnPrimaryContainer = Color(0xFFF2F2F2)
val MonoLightSecondary = Color(0xFF5C5C5C)
val MonoLightOnSecondary = Color(0xFFFFFFFF)
val MonoLightSecondaryContainer = Color(0xFFE2E2E2)
val MonoLightOnSecondaryContainer = Color(0xFF1C1C1C)
val MonoLightTertiary = Color(0xFF6B6B6B)
val MonoLightOnTertiary = Color(0xFFFFFFFF)
val MonoLightTertiaryContainer = Color(0xFFE8E8E8)
val MonoLightOnTertiaryContainer = Color(0xFF1F1F1F)
val MonoLightBackground = Color(0xFFF6F6F6)
val MonoLightOnBackground = Color(0xFF1A1A1A)
val MonoLightSurface = Color(0xFFF6F6F6)
val MonoLightOnSurface = Color(0xFF1A1A1A)
val MonoLightSurfaceVariant = Color(0xFFE4E4E4)
val MonoLightOnSurfaceVariant = Color(0xFF474747)
val MonoLightSurfaceContainerLowest = Color(0xFFFFFFFF)
val MonoLightSurfaceContainerLow = Color(0xFFF1F1F1)
val MonoLightSurfaceContainer = Color(0xFFEBEBEB)
val MonoLightSurfaceContainerHigh = Color(0xFFE4E4E4)
val MonoLightSurfaceContainerHighest = Color(0xFFDEDEDE)
val MonoLightOutline = Color(0xFF777777)
val MonoLightOutlineVariant = Color(0xFFC6C6C6)
val MonoLightInverseSurface = Color(0xFF2F2F2F)
val MonoLightInverseOnSurface = Color(0xFFF1F1F1)
val MonoLightInversePrimary = Color(0xFFC8C8C8)

val MonoDarkPrimary = Color(0xFFE6E6E6)
val MonoDarkOnPrimary = Color(0xFF1A1A1A)
val MonoDarkPrimaryContainer = Color(0xFF3A3A3A)
val MonoDarkOnPrimaryContainer = Color(0xFFF0F0F0)
val MonoDarkSecondary = Color(0xFFC4C4C4)
val MonoDarkOnSecondary = Color(0xFF2A2A2A)
val MonoDarkSecondaryContainer = Color(0xFF3A3A3A)
val MonoDarkOnSecondaryContainer = Color(0xFFE8E8E8)
val MonoDarkTertiary = Color(0xFFB8B8B8)
val MonoDarkOnTertiary = Color(0xFF1F1F1F)
val MonoDarkTertiaryContainer = Color(0xFF3F3F3F)
val MonoDarkOnTertiaryContainer = Color(0xFFE6E6E6)
val MonoDarkBackground = Color(0xFF121212)
val MonoDarkOnBackground = Color(0xFFE8E8E8)
val MonoDarkSurface = Color(0xFF121212)
val MonoDarkOnSurface = Color(0xFFE8E8E8)
val MonoDarkSurfaceVariant = Color(0xFF3A3A3A)
val MonoDarkOnSurfaceVariant = Color(0xFFC4C4C4)
val MonoDarkSurfaceContainerLowest = Color(0xFF0D0D0D)
val MonoDarkSurfaceContainerLow = Color(0xFF1A1A1A)
val MonoDarkSurfaceContainer = Color(0xFF1F1F1F)
val MonoDarkSurfaceContainerHigh = Color(0xFF2A2A2A)
val MonoDarkSurfaceContainerHighest = Color(0xFF353535)
val MonoDarkOutline = Color(0xFF8E8E8E)
val MonoDarkOutlineVariant = Color(0xFF3F3F3F)
val MonoDarkInverseSurface = Color(0xFFE6E6E6)
val MonoDarkInverseOnSurface = Color(0xFF2A2A2A)
val MonoDarkInversePrimary = Color(0xFF4A4A4A)
